spring.application.name=lessonrest
server.port=24110
api.base-url=http://localhost:24110/api/v1.0/

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/project
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.change-log=classpath:/changelog/db.changelog-master.xml
# spring.liquibase.contexts=dev
#  spring.liquibase.default-schema=distcomp
logging.level.liquibase=DEBUG

spring.jpa.hibernate.naming.physical-strategy=com.example.LessonRest.repository.TblPhysicalNamingStrategy
spring.jpa.properties.hibernate.default_schema=distcomp


# Logging configuration
logging.config=classpath:log4j2.xml
logging.level.com.example.LessonRest=INFO
logging.file.name=app.log
logging.file.max-size=10MB

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,liquibase

# Hidden HTTP method filter
spring.mvc.hiddenmethod.filter.enabled=true